version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: NZ
  open-pull-requests-limit: 2
  labels:
  - "docker :whale:"
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: NZ
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: cupy-cuda102
    versions:
    - ">= 8.1.0.a, < 8.1.1"
  - dependency-name: cython
    versions:
    - ">= 0.29.19.a, < 0.29.20"
  - dependency-name: dask
    versions:
    - ">= 2.27.a, < 2.28"
  - dependency-name: dask
    versions:
    - ">= 2.28.a, < 2.29"
  - dependency-name: dask-labextension
    versions:
    - ">= 5.0.1.a, < 5.0.2"
  - dependency-name: distributed
    versions:
    - ">= 2.30.1.a, < 2.30.2"
  - dependency-name: jupyterlab
    versions:
    - ">= 2.1.4.a, < 2.1.5"
  - dependency-name: jupytext
    versions:
    - ">= 1.6.a, < 1.7"
  - dependency-name: llvmlite
    versions:
    - ">= 0.33.0.a, < 0.33.1"
  - dependency-name: lxml
    versions:
    - ">= 4.5.1.a, < 4.5.2"
  - dependency-name: matplotlib
    versions:
    - ">= 3.3.1.a, < 3.3.2"
  - dependency-name: pyarrow
    versions:
    - "> 1.0.1"
  - dependency-name: pyarrow
    versions:
    - ">= 2.0.0.a, < 2.0.1"
  - dependency-name: pytest
    versions:
    - ">= 6.0.0.a, < 6.0.1"
  - dependency-name: pytest
    versions:
    - ">= 6.0.1.a, < 6.0.2"
  - dependency-name: tqdm
    versions:
    - ">= 4.46.1.a, < 4.46.2"
  - dependency-name: tqdm
    versions:
    - ">= 4.49.a, < 4.50"
  - dependency-name: tqdm
    versions:
    - ">= 4.54.1.a, < 4.54.2"
  - dependency-name: distributed
    versions:
    - 2021.1.1
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: NZ
  open-pull-requests-limit: 2
